/**
 * Copyright (C) 2011 LShift Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.lshift.hibernate.migrations;

import org.hibernate.cfg.Configuration;
import org.junit.Test;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;

import static net.lshift.hibernate.migrations.HibernateHelper.mockExecutablePreparedStatement;
import static org.easymock.EasyMock.*;

/**
 * Tests for table creation.
 */
public class CreateTableBuilderTest {
  @Test
  public void shouldCreateTableWithColumnThatHasDefaultSize() throws Exception {
    MigrationBuilder mb = new MigrationBuilder(HibernateHelper.configuration());
    mb.createTable("foo").column("bar", Types.INTEGER, false).pk("bar");

    Connection conn = createStrictMock(Connection.class);
    expect(conn.prepareStatement("create table foo (bar integer not null, primary key (bar))")).
        andReturn(mockExecutablePreparedStatement());
    replay(conn);

    mb.apply(conn);
    verify(conn);
  }

  @Test
  public void shouldCreateTableWithColumnThatHasExplicitSize() throws Exception {
    MigrationBuilder mb = new MigrationBuilder(HibernateHelper.configuration());
    mb.createTable("foo").column("bar", Types.INTEGER, false).column("baz", Types.VARCHAR, 4096, true).pk("bar");

    Connection conn = createStrictMock(Connection.class);
    expect(conn.prepareStatement("create table foo (bar integer not null, baz varchar(4096), primary key (bar))")).
        andReturn(mockExecutablePreparedStatement());
    replay(conn);

    mb.apply(conn);
    verify(conn);
  }

  @Test
  public void shouldCreateTableWithCompoundPrimaryKey() throws Exception {
    MigrationBuilder mb = new MigrationBuilder(HibernateHelper.configuration());
    mb.createTable("foo").
        column("bar", Types.INTEGER, false).
        column("baz", Types.VARCHAR, 4096, true).
        pk("bar", "baz");

    Connection conn = createStrictMock(Connection.class);
    expect(conn.prepareStatement("create table foo (bar integer not null, baz varchar(4096) not null, primary key (bar, baz))")).
        andReturn(mockExecutablePreparedStatement());
    replay(conn);

    mb.apply(conn);
    verify(conn);
  }

  @Test
  public void shouldCreateTableWithIdentityColumnWhenDialectSupportsIdentityColumns() throws Exception {
    String[] statements = {
      "create table foo (bar integer generated by default as identity (start with 1), baz varchar(4096), primary key (bar))"
    };
    expectCreateTableStatements(HibernateHelper.configuration(), true, statements);
  }

  @Test
  public void shouldCreateTableWithSequenceWhenDialectDoesntSupportIdentityColumns() throws Exception {
    Configuration config = new Configuration().setProperty("hibernate.dialect", "org.hibernate.dialect.Oracle10gDialect");
    String[] statements = {
      "create table foo (bar number(10,0) not null, baz long, primary key (bar))",
      "create sequence foo_sequence"
    };
    expectCreateTableStatements(config, true, statements);
  }

  @Test
  public void shouldNotCreateTableWithSequenceUnlessNativeIdentityGeneratorRequested() throws Exception {
    Configuration config = new Configuration().setProperty("hibernate.dialect", "org.hibernate.dialect.Oracle10gDialect");
    String[] statements = {
      "create table foo (bar number(10,0) not null, baz long, primary key (bar))"
    };
    expectCreateTableStatements(config, false, statements);
  }

  @Test
  public void shouldPartitionTableWhenDialectExtensionSupportsPartitioningAndPartitionIsRequested() throws Exception {
    Configuration config = new Configuration().setProperty("hibernate.dialect", "org.hibernate.dialect.Oracle10gDialect");

    String statement = "create table foo (bar number(10,0) not null, baz varchar2(1024 char), haz varchar2(1024 char), primary key (bar)) partition by hash(baz,haz) partitions 10";

    MigrationBuilder mb = new MigrationBuilder(config);
    mb.createTable("foo").
      column("bar", Types.INTEGER, false).
      column("baz", Types.VARCHAR, 1024, true).
      column("haz", Types.VARCHAR, 1024, true).
      pk("bar").
      hashPartitions(10, "baz","haz");

    Connection conn = createStrictMock(Connection.class);
    expect(conn.prepareStatement(statement)).andReturn(mockExecutablePreparedStatement());

    replay(conn);

    mb.apply(conn);
    verify(conn);
  }

  private void expectCreateTableStatements(Configuration config, boolean nativeIdentityGenerator, String... statements) throws SQLException {
    MigrationBuilder mb = new MigrationBuilder(config);
    CreateTableBuilder cb = mb.createTable("foo").
        column("bar", Types.INTEGER, false).
        column("baz", Types.VARCHAR, 4096, true).
        pk("bar");

    if (nativeIdentityGenerator) {
      cb.withNativeIdentityGenerator();
    }

    Connection conn = createStrictMock(Connection.class);

    for (String statement : statements) {
      expect(conn.prepareStatement(statement)).andReturn(mockExecutablePreparedStatement());
    }

    replay(conn);

    mb.apply(conn);
    verify(conn);
  }
}
